### ISSUE TITLE
procedure how to generate docs for mdbook

### ISSUE THREAD

**Issue by despiegk** [freeflowuniverse/spiderlib#12]
- [ ] write in manual how we should generate docs using github pages & actions in most easy way
- [x] have example how we did it now in https://github.com/threefoldfoundation/books/tree/main/books/abundance_internet or better
- [x] the result needs to be docs in github pages but not in repo itself
- [x] need to show icon on home page so we see the docs have been build
- [x] lets make sure this happens properly on spiderlib, crystallib, vbuilder and web3gw

**Comment by brandonpille** [comment]
Makes sense. We are already doing this for web3gw: https://github.com/threefoldtech/web3_proxy/blob/development/.github/workflows/documentation.yaml. I'll pick this up whenever I can.

**Comment by alichaddad** [comment]
Pipeline for generating the docs is now added to: `spiderlib`, `crystallib` and `vbuilder`. Each repo now has a github page that hosts the repo's documentation.

**Comment by brandonpille** [comment]
@alichaddad thank  you for the changes, it looks good! But could you please do the first bullet point?

**Comment by alichaddad** [comment]
@brandonpille which manual should this information be added to?

**Comment by brandonpille** [comment]
I assume each of the repos should have a manual. If it has it add it to the manual there and if not add in the readme. It's important that people who are new to the repo that they quickly know how the documentation is generated and where it is uploaded.
